### ISSUE TITLE
Jemalloc patch

### ISSUE THREAD

**Issue by theofficialgman** [Radiicall/lwjgl-jemalloc-m1#1]
I got notified you forked my multimc meta.

I assume you now realize I already updated the universal meta (used for gdlauncher), the multimc meta, and the prism launcher meta to use the jemalloc 16K pages compatible binary?

**Comment by Radiicall** [comment]
ohhh, I didnt realize.. Thanks for informing me about it! I had this set up months ago with my own jemalloc stuff back when the driver *barely* worked, so I was trying to set it up again.

I will delete this repo then!
